server:
  port: 8080

spring:
  cache:
    type: redis
    redis:
      time-to-live: 600s
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      use_sql_comments: true
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stove?serverTimezone=Asia/Seoul
    username: root
    password:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000
      connection-init-sql: set wait_timeout = 600

feign:
  naver-search:
    url: https://openapi.naver.com/v1/search