server:
  port: 8080

spring:
  cache:
    type: redis
    redis:
      time-to-live: 600s
  redis:
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.format_sql: true
      use_sql_comments: true
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
