server:
  port: 8080

jwt:
  secret: ENC(655UoZCEmU8akaODRke7SA==)

spring:
  cache:
    type: redis
    redis:
      time-to-live: 600s
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      use_sql_comments: true
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Lz4D5vDGF9FUctGPAMdmbqEkxBqkEcuV5hdDDyQ69fzJNd+ZTtSJq0JsLuFK4IYpa4SgerAF1MUNVNdQ7/HtZw==)
    username: ENC(uT/vxA3BYhq6z8lLKcHaRA==)
    password: ENC(6Yzd0d5qKhZhMR0ko/BGHA==)

cloud:
  aws:
    credentials:
      accessKey: ENC(+lAlU3n8oQUf0haAXHL6waN2LK+gD17Nk++3w5XhZeM=)
      secretKey: ENC(o5MtoVKAi4cCZc3NS3oPdaa0Mzdblu2kpIWkV3Herp1PSZ8LciG5novwaW7oBkV7IBiT3sa96x0=)
    s3:
      bucket: ENC(GXfZtMLnvNXWe5CtBPHcWfFkpzfDSycm)
    region:
      static: ap-northeast-2
