spring:
  profiles:
    active: local


springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true

jasypt:
  encryptor:
    password: ${JASYPT_SECRETE_KEY}
